import { Roboto } from 'next/font/google'
import "./globals.css";


const robotFont = Roboto({
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotFont.className} bg-slate-50` } 
        
      >
        
        {children}
      </body>
    </html>
  );
}
